default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'testapp_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  # reconnect: true # reconnect option is deprecated with newer mysql database versions

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'testapp_development' %>

test:
  <<: *default
  database: testapp_test

production:
  <<: *default
  database: testapp_production
  url: <%= ENV['DATABASE_URL'] %>
